FROM rust:1.92.0-bullseye AS build

ARG APP_NAME=backend
WORKDIR /build

RUN apt-get update && apt-get install -y pkg-config libssl-dev

COPY . .
RUN cargo build --release
RUN cp ./target/release/$APP_NAME /bin/server

FROM debian:bullseye-slim AS final

RUN apt-get update && apt-get install -y \
    ca-certificates \
    libssl1.1 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=build /bin/server /usr/local/bin/server

EXPOSE 3000

CMD ["/usr/local/bin/server"]